spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.1.195:5432/student
    username: postgres
    password: postgres
server:
  servlet:    context-path: /sample
  